#
# Brusselator
#
[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 300.0                               # End time [s]

[Numerics]
    dt = 0.1                                     # Time step size [s], if dt == 0: then stationary problem
    integration = "delta_formulation"  # "delta_formulation", "runge_kutta_4"
    iter_max = 25                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Physics]
    k1 = 1.0                                     
    k2 = 2.5
