# Logging = "matrix"  # "iterations", "matrix"

[Domain]
    mesh_file = "geometry/63x63_net.nc"
    bed_level_file = "geometry/63x63.bed"  # uniform depth

[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 900.0                                # End time [s]
        
[Initial]
    ini_vars = ["zeta", "zeta_gauss_hump"]
    gauss_amp = 0.01 # amplitude of the gaussian hump
    gauss_mu = 0.0    # location of the top of the gaussian hump
    gauss_sigma = 350.0    # width of the gaussian hump

[Boundary] # north, east, south, west
    bc_type = ["mooiman", "mooiman", "mooiman", "mooiman"] # Type "borsboom", "dirichlet", "mooiman" 
    bc_vars = ["zeta", "zeta", "zeta", "zeta"]
    bc_vals = [0.0, 0.0, 0.0, 0.0]
    bc_absorbing = [true, true, true, true]
    treg = 150.0                                  # Regularization time boundary signal
    eps_bc_corr = 1.0e-2

[Physics]
    g = 10.0                        # Gravitational acceleration
    do_continuity = true            # continuity equation
    do_q_equation = true            # q momentum equation
    do_r_equation = true            # r momentum equation
    do_q_convection = false         # Include momentum convection term
    do_r_convection = false         # Include momentum convection term
    do_viscosity = false            # Include momentum viscosity term
    viscosity = 0.01
    do_bed_shear_stres = false      # Include momentum bed shear stress term
    chezy_coefficient = 50.0        # Chezy coefficient

[Numerics]
    dt = 5.0                        # Time step size [s], if dt == 0: then stationary problem
    iter_max = 25                   # Maximum number of nonlinear iterations
    theta = 0.501                   # Implicitness factor (0.5 <= theta <= 1.0)
    regularization_init = true
    regularization_iter = false
    regularization_time = false
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 0.01   # [s]
    dt_map = 0.01   # [s] 