[Domain]
    Lx = 1000.0                                   # Domain length [m]
    depth = 4.0    # bathymetry below reference level [m]
    geometry_type = "WavyBedGeometry"

[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 43200.0                               # End time [s]
        
[Initial]
    ini_vars = ["zeta"]
    gauss_mu = 0.0    # location of the top of the gaussian hump
    gauss_sigma = 700.0    # width of the gaussian hump
    a0 = 0.0 # amplitude of the gaussian hump at the boundary

[Boundary]
    bc_type = ["borsboom", "borsboom"]            # Type "mooiman", "borsboom"
    bc_vars = ["q", "zeta"]                       # Incoming signal  
    bc_vals = [4.0, 0.0]                          # The inflow discharge q should be 4.0
    bc_absorbing = [true, true]
    treg = 600.0                                 # Regularization time on boundary
    eps_bc_corr = 1.0e-2

[Physics]
    g = 10.0                                      # Gravitational acceleration
    momentum_convection = true                    # Include momentum convection term
    momentum_bed_shear_stress = false             # Include bed shear stress
    momentum_viscosity = false                    # Include bed shear stress
    chezy_coefficient = 50.0                      # Chezy coefficient
    viscosity = 1.25                              # half Dx 

[Numerics]
    dt = 0.0                                      # Time step size [s], if dt == 0: then stationary problem
    dx = 5.0                                      # Grid size [m]
    iter_max = 50                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 5.0   # [s]
    dt_map = 15.0  # [s] 
