# Logging = "matrix"  # "iterations", "matrix"

[Boundary] # north, east, south, west
    treg = 150.0                                  # Regularization time boundary signal
    eps_bc_corr = 1.0e-2
    bc_signals   = ["constant", "constant", "constant", "constant"]
    bc_type = ["borsboom", "borsboom", "borsboom", "borsboom"] # Type "borsboom", "free_slip", "mooiman" 
    bc_vars = ["zeta", "zeta", "zeta", "zeta"]
    bc_vals = [0.0, 0.0, 0.0, 0.0]

[Domain]
    mesh_file = "geometry/62x62_net.nc"
    bed_level_file = "geometry/62x62_tile.dep"

[Initial]
    ini_vals      = [0.0, 0.0, 0.0]
    ini_vars      = ["zeta_constant", "u_constant", "v_constant"]

[Physics]
    g = 10.0                        # Gravitational acceleration
    do_continuity = true            # continuity equation
    do_q_equation = true            # q momentum equation
    do_r_equation = true            # r momentum equation
    do_q_convection = false         # Include momentum convection term
    do_r_convection = false         # Include momentum convection term
    do_bed_shear_stress = false     # Include momentum bed shear stress term
    do_viscosity = false            # Include momentum viscosity term
    viscosity = 0.01
    chezy_coefficient = 50.0        # Chezy coefficient

[Numerics]
    dt                  = 2.0   # Time step size [s], if dt == 0: then stationary problem
    theta               = 0.5   # Implicitness factor (0.5 <= theta <= 1.0)
    c_psi               = 4.0
    iter_max            = 25  # Maximum number of nonlinear iterations
    eps_newton          = 1.0e-12
    eps_bicgstab        = 1.0e-06
    regularization_init = true
    regularization_iter = false
    regularization_time = false

[Output]
    dt_his    = 0.01   # [s]
    dt_map    = 0.01   # [s] 
    dt_screen = 300.0

[Time]
    tunit  = "s"
    tstart = 0.0                                  # Start time [s]
    tstop  = 4.0                                  # End time [s]
