# Logging = "matrix"  # "iterations", "matrix"

[Domain]
    MeshFile = "100x24_net.nc"
    BedLevelFile = "102x26_sloped.dep"
    
[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 900.0                                # End time [s]
        
[Initial]
    ini_vars = ["zeta", "q", "r"]
    ini_vals = [0.1, 0.0, 0.0]

[Boundary] # north, east, south, west
    bc_type = ["dirichlet", "mooiman", "dirichlet", "mooiman"] # Type "borsboom", "dirichlet", "mooiman" 
    bc_vars = ["-", "q", "-", "zeta"]
    bc_vals = [0.0, 1.0, 0.0, 0.0]
    bc_absorbing = [false, true, false, true]
    treg = 150.0                                  # Regularization time boundary signal
    eps_bc_corr = 1.0e-2

[Physics]
    g = 10.0                                      # Gravitational acceleration
    do_continuity = true                   # continuity equation
    do_q_equation = true                   # q momentum equation
    do_r_equation = true                   # r momentum equation
    do_convection = false                   # Include momentum convection term
    do_viscosity = false                   # Include momentum viscosity term
    do_bed_shear_stres = true                   # Include momentum bed shear stress term

[Numerics]
    dt = 2.0                                      # Time step size [s], if dt == 0: then stationary problem
    iter_max = 25                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    regularization_init = true
    regularization_iter = false
    regularization_time = false
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 0.01   # [s]
    dt_map = 0.01   # [s] 