# Logging = "iterations" # "iterations", "matrix" 

[Domain]
    Lx = 500.0                                    # Domain length [m]
    geometry_type = "WeirBorsboom2000Geometry"

[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 7200.0                               # End time [s]
 
[Initial]
    ini_vars = ["zeta"]
    gauss_mu = 0.0                                # location of the top of the gaussian hump
    gauss_sigma = 700.0                           # width of the gaussian hump
    a0 = 0.0                                      # amplitude of the gaussian hump at the boundary

[Boundary]
    bc_type = ["borsboom", "borsboom"]            # Type "mooiman", "borsboom"
    bc_vars = ["q", "zeta"]                       # Incoming signal  
    bc_vals = [19.8656, -3.0]                     # The inflow discharge
    bc_absorbing = [true, true]
    treg = 300.0                                  # Regularization time on boundary
    eps_bc_corr = 1.0e-02

 [Physics]
    g = 10.0                                      # Gravitational acceleration
    momentum_convection = true                    # Include momentum convection term
    momentum_bed_shear_stress = false             # Include bed shear stress
    momentum_viscosity = true                     # Include bed shear stress
    chezy_coefficient = 50.0                      # Chezy coefficient
    viscosity = 0.01

[Numerics]
    dt = 4.0                                      # Time step size [s], if dt == 0: then stationary problem
    dx = 20.0                                      # Grid size [m]
    c_psi = 4.0
    iter_max = 50                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    use_eq8 = true
    regularization_init = true
    regularization_iter = false
    regularization_time = true
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 0.01    # [s]
    dt_map = 1.00   # [s] 
