[Domain]
    Lx = 12000.0                                  # Domain length [m]
    Ly = 12000.0                                  # Domain length [m]
    depth = 10.0    # bathymetry below reference level [m]
    geometry_type = "UniformGeometry"

[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 1800.0                                # End time [s]

[Initial]
    ini_vars = ["zeta", "zeta_GaussHump"]
    gauss_amp = 0.01 # amplitude of the gaussian hump
    gauss_mu = 0.0  # location of the top of the gaussian hump
    gauss_sigma = 350.0  # width of the gaussian hump

[Boundary] # north, east, south, north
    bc_type = ["dirichlet", "dirichlet", "dirichlet", "dirichlet"] # Type "mooiman", "borsboom", "dirichlet"
    bc_vars = ["zeta", "zeta", "zeta", "zeta"]                       # Incoming signal  
    bc_vals = [0.0, 0.0, 0.0, 0.0]                        
    bc_absorbing = [false, false, false, false]    
    treg = 150.0                                  # Regularization time boundary signal
    eps_bc_corr = 1.0e-2

[Physics]
    g = 10.0                                      # Gravitational acceleration
    do_continuity = true                   # q momentum equation
    do_q_equation = true                   # q momentum equation
    do_r_equation = true                   # r momentum equation
    do_convection = false                   # Include momentum convection term
    do_viscosity = false                   # Include momentum viscosity term
    do_bed_shear_stres = false                   # Include momentum bed shear stress term

[Numerics]
    dt = 5.0                                      # Time step size [s], if dt == 0: then stationary problem
    dx = 50.0                                     # Grid size [m]
    dy = 50.0                                     # Grid size [m]
    iter_max = 25                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    regularization_init = true
    regularization_iter = false
    regularization_time = false
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 0.01   # [s]
    dt_map = 0.01  # [s]
