[Domain]
    Lx = 18000.0                                  # Domain length [m]
    depth = 10.0    # bathymetry below reference level [m]
    geometry_type = "UniformGeometry"

[Time]
    tstart = 0.0                                  # Start time [s]
    tstop = 28800.0                               # End time [s]
        
[Initial]
    ini_vars = ["zeta"]
    gauss_mu = 4500.0    # location of the top of the gaussian hump
    gauss_sigma = 700.0    # location of the top of the gaussian hump
    a0 = 0.2 # amplitude of the gaussian hump at the boundary

[Boundary]
    bc_type = ["borsboom", "borsboom"]              # Type "mooiman", "borsboom"
    bc_vars = ["q", "zeta"]                       # Incoming signal  
    bc_vals = [0.05, 0.005]                          # The inflow discharge
    bc_absorbing = [true, true]
    treg = 600.0                                  # Regularization time on boundary
    eps_bc_corr = 1.0e-2

[Physics]
    g = 10.0                                      # Gravitational acceleration
    momentum_convection = true                    # Include momentum convection term

[Numerics]
    dt = 10.0                                     # Time step size [s], if dt == 0: then stationary problem
    dx = 20.0                                     # Grid size [m]
    iter_max = 25                                 # Maximum number of nonlinear iterations
    theta = 0.501                                 # Implicitness factor (0.5 <= theta <= 1.0)
    eps_newton = 1.0e-12
    eps_bicgstab = 1.0e-12

[Output]
    dt_his = 1.0   # [s]
    dt_map = 1.0  # [s] 
